In [1]:
import numpy as np


In [6]:
my_list =[1,2,3,4,5]
arr = np.array(my_list)

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
arr


array([1, 2, 3, 4, 5])

In [11]:
arr.shape

(5,)

In [29]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr1 = np.array([my_list1,my_list2,my_list3])

In [22]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
arr1.shape

(3, 5)

In [32]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
arr1[0][4]

5

In [30]:
arr1[0:3,:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
arr1[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [36]:
arr1[0:4,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [39]:
arr =np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr =np.arange(0,10 ,step =2)
arr

array([0, 2, 4, 6, 8])

In [41]:
arr1[0:4,1:4] = 100;
arr1

array([[  1, 100, 100, 100,   5],
       [  6, 100, 100, 100,  10],
       [ 11, 100, 100, 100,  15]])

In [42]:
## linspace
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [52]:
my_list1=[1,2,3,4,5,6,7,8,9]
arr2 = np.array(my_list1)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
value =2
arr2>value

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [55]:
arr2*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
## if want value parmenant
arr2[arr2 <5]

array([1, 2, 3, 4])

In [70]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [73]:
np.zeros(4)

array([0., 0., 0., 0.])

In [74]:
np.ones((2,5),dtype =int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [78]:
# give random value frome 0 to 1 in range(--)
np.random.rand(4,4)

array([[0.20973263, 0.86512338, 0.21004365, 0.59714425],
       [0.32135472, 0.38544604, 0.12753392, 0.91175208],
       [0.87859083, 0.45086556, 0.34205412, 0.38268222],
       [0.1716748 , 0.14553652, 0.68457417, 0.75286802]])